bundler_args: --without development

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode

branches:
  only:
    - master
    - development

script: bundle exec rspec spec
